### ISSUE TITLE
UI bug: two capital letters entered if ignoring autocomplete in text fields

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#243]
See attached video
Also, may I suggest enlarging the X element at the right end of the field?

https://user-images.githubusercontent.com/1769078/129400503-981a3c7f-0b8b-41bf-a2b8-fe31c77e54a8.MP4

**Comment by ericberman** [comment]
I can't do anything about the x - iOS draws that, not me.  (Though it is awfully small in your screenshot!)  I could try increasing the font size, since I think it's tied to that, but that may impact the layout in other ways.

I'm not quite sure what the bug is.  In your video, you type "C", which autocompletes to "Conrad".  You then type 'D", which then has no autocompletion, but "CD" remains.  So what's the issue?

**Comment by zartom** [comment]
I'm not in caps lock. It should be "Cd" not "CD"

**Comment by ericberman** [comment]
Weird, looks like an iOS issue deciding whether or not to keep caps on.  I set the field to be either all capitals (e.g., used for things like "First Time to Airport", since airports are generally all caps), or to word-based capitalization (People's names, like Name of PIC, in this case), or to sentence capitalization (first letter after a period and a space).  But it's iOS's control that handles the actual capitalization.

But if you hit backspace then type "d", the caps button resets.

I increased the size of the "x" a bit, but otherwise, I don't think I want to wade into the complexities of working around iOS's inability to determine word boundaries properly.
