### ISSUE TITLE
Suggestion: if template is used, add new property to it directly from new flight activity from mobile app 

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#246]
Title

**Comment by ericberman** [comment]
Hmm...that's really hard to do in a clean manner, especially since templates stack and are cascading.  I.e., it's not uncommon to have multiple templates apply at once.  For example, you can have a template that arises because a specific aircraft is chosen, and then one or more templates added on top of that.

So it's inherently ambiguous to which template you'd be adding the property.

My inclination is to leave this centralized on the server...
