### ISSUE TITLE
Editing a Pending Flight when online and then exiting the screen after losing connectivity removes it from Recent Flight

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#345]
Case in point: Entering information on a Pending flight before startup, and adding to it while in cruise without internet connectivity.

Bonus point: when editing it says "Excellent GPS reception" + "On Ground" status, even while in cruise

**Comment by zartom** [comment]
I created the pending flight on the web. Then edit it on an iPad
Also I didn't refresh. I exited the editing view while offline, of the pending flight which was opened when online. Also on iPad obviously

**Comment by ericberman** [comment]
But when you got back online and then refreshed, did it re-appear in the recent flights list?

**Comment by zartom** [comment]
Yes without my changes and edits

בתאריך יום ו׳, 15 בנוב׳ 2024, 18:40, מאת Eric Berman ‏<
***@***.***>:

**Comment by ericberman** [comment]
That makes sense - you just tapped "back" rather than "add" (to save the flight to your logbook) or "save as pending flight".  Either of those would stick the updated flight into the queue to be updated.  But just going back doesn't queue up the edits, so when you go back online, it gets overwritten.  

So I'm going to close this specific bug as by-design.  But issue #344 is legitimate.

**Comment by zartom** [comment]
You mean instead of tapping "update".
Also it wasn't intentional so I lost all the new data

בתאריך שבת, 16 בנוב׳ 2024, 02:31, מאת Eric Berman ***@***.***

**Comment by ericberman** [comment]
Yes, because going back is sort of equivalent to "cancel".  But it's actually a bit looser than that.  Simply going back doesn't discard the change!  It's still in memory, the edits are still in progress.  If you go back and then tap on the pending flight again, the changes from before are still reflected!  They're just not yet committed.  As a result, any update from the website will overwrite those changes.  But if you commit the change, then it's...well, committed.

**Comment by ericberman** [comment]
Oh, and to your point, no, I meant "add", not "update."  There is no "update" for a pending flight.  You can "Add", which means "save it to my logbook", or you can "Save as pending flight", which will save it to your pending flights (as a new flight if it hasn't previously been saved as a pending flight, or as an updated version of an existing pending flight).
